//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CST.LePoint.Intervention.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesMenus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesMenus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CST.LePoint.Intervention.Properties.ResourcesMenus", typeof(ResourcesMenus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affectation Gratuités.
        /// </summary>
        internal static string AffectationGratuites {
            get {
                return ResourceManager.GetString("AffectationGratuites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse BI Employé.
        /// </summary>
        internal static string AnalyseBI {
            get {
                return ResourceManager.GetString("AnalyseBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse BI Bus.
        /// </summary>
        internal static string AnalyseBIBus {
            get {
                return ResourceManager.GetString("AnalyseBIBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse BI &amp; Intervention.
        /// </summary>
        internal static string AnalyseBIIntervention {
            get {
                return ResourceManager.GetString("AnalyseBIIntervention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse BI Trace.
        /// </summary>
        internal static string AnalyseBITrace {
            get {
                return ResourceManager.GetString("AnalyseBITrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Propos.
        /// </summary>
        internal static string APropos {
            get {
                return ResourceManager.GetString("APropos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string ArticleListe {
            get {
                return ResourceManager.GetString("ArticleListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformer BC en OT.
        /// </summary>
        internal static string BC_OT {
            get {
                return ResourceManager.GetString("BC_OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BI Abir.
        /// </summary>
        internal static string BIAbir {
            get {
                return ResourceManager.GetString("BIAbir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Tracking.
        /// </summary>
        internal static string BusTracking {
            get {
                return ResourceManager.GetString("BusTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chantiers.
        /// </summary>
        internal static string Chantier {
            get {
                return ResourceManager.GetString("Chantier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Divers.
        /// </summary>
        internal static string ChargesDiversListe {
            get {
                return ResourceManager.GetString("ChargesDiversListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit Ajout/Modif.
        /// </summary>
        internal static string Circuit {
            get {
                return ResourceManager.GetString("Circuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit Direct.
        /// </summary>
        internal static string CircuitDirect {
            get {
                return ResourceManager.GetString("CircuitDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit.
        /// </summary>
        internal static string CircuitNormal {
            get {
                return ResourceManager.GetString("CircuitNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string ClientListe {
            get {
                return ResourceManager.GetString("ClientListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convention Client.
        /// </summary>
        internal static string ConventionClient {
            get {
                return ResourceManager.GetString("ConventionClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convention Client ( ADMIN ).
        /// </summary>
        internal static string ConventionClientAdmin {
            get {
                return ResourceManager.GetString("ConventionClientAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deplacement Client Circuit.
        /// </summary>
        internal static string DeplacementClientCircuit {
            get {
                return ResourceManager.GetString("DeplacementClientCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droits d&apos;accés.
        /// </summary>
        internal static string DroitsAcces {
            get {
                return ResourceManager.GetString("DroitsAcces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employés.
        /// </summary>
        internal static string Employés {
            get {
                return ResourceManager.GetString("Employés", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipes.
        /// </summary>
        internal static string EquipeListe {
            get {
                return ResourceManager.GetString("EquipeListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Famille opération.
        /// </summary>
        internal static string FamilleOpération {
            get {
                return ResourceManager.GetString("FamilleOpération", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier.
        /// </summary>
        internal static string Fichier {
            get {
                return ResourceManager.GetString("Fichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transformation Interventions en BLs.
        /// </summary>
        internal static string Intervention_BLListe {
            get {
                return ResourceManager.GetString("Intervention_BLListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des Interventions.
        /// </summary>
        internal static string InterventionListe {
            get {
                return ResourceManager.GetString("InterventionListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opérations.
        /// </summary>
        internal static string Opérations {
            get {
                return ResourceManager.GetString("Opérations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordonnancement des Tournées.
        /// </summary>
        internal static string OrdonnancementdesTournées {
            get {
                return ResourceManager.GetString("OrdonnancementdesTournées", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordres de Visite.
        /// </summary>
        internal static string OTListe {
            get {
                return ResourceManager.GetString("OTListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Collecte.
        /// </summary>
        internal static string PCollecteListe {
            get {
                return ResourceManager.GetString("PCollecteListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planification Automatique.
        /// </summary>
        internal static string PlanificationAutomatique {
            get {
                return ResourceManager.GetString("PlanificationAutomatique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier la Planification Automatique.
        /// </summary>
        internal static string PlanificationAutomatiqueModif {
            get {
                return ResourceManager.GetString("PlanificationAutomatiqueModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Collecte.
        /// </summary>
        internal static string PointCollecte {
            get {
                return ResourceManager.GetString("PointCollecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivités.
        /// </summary>
        internal static string ProductiviteListe {
            get {
                return ResourceManager.GetString("ProductiviteListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string Quitter {
            get {
                return ResourceManager.GetString("Quitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visites.
        /// </summary>
        internal static string RattachementListe {
            get {
                return ResourceManager.GetString("RattachementListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rôles.
        /// </summary>
        internal static string RoleListe {
            get {
                return ResourceManager.GetString("RoleListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellites.
        /// </summary>
        internal static string Satellites {
            get {
                return ResourceManager.GetString("Satellites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sécurité.
        /// </summary>
        internal static string Securite {
            get {
                return ResourceManager.GetString("Securite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts.
        /// </summary>
        internal static string ShiftListe {
            get {
                return ResourceManager.GetString("ShiftListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Société.
        /// </summary>
        internal static string SocieteListe {
            get {
                return ResourceManager.GetString("SocieteListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi Convention.
        /// </summary>
        internal static string SuiviConvention {
            get {
                return ResourceManager.GetString("SuiviConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi Planification.
        /// </summary>
        internal static string SuiviPlanification {
            get {
                return ResourceManager.GetString("SuiviPlanification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs.
        /// </summary>
        internal static string UtilisateurListe {
            get {
                return ResourceManager.GetString("UtilisateurListe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation de Visite.
        /// </summary>
        internal static string ValidationPlanif {
            get {
                return ResourceManager.GetString("ValidationPlanif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Véhicules.
        /// </summary>
        internal static string Véhicules {
            get {
                return ResourceManager.GetString("Véhicules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivi Visite Manquante.
        /// </summary>
        internal static string VisiteManquante {
            get {
                return ResourceManager.GetString("VisiteManquante", resourceCulture);
            }
        }
    }
}
