// <auto-generated />
using System;
using CollectManagement.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260522155516_UpdateRoleUtilisateurAndAddUtilisateurSite")]
    partial class UpdateRoleUtilisateurAndAddUtilisateurSite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollectManagement.Domain.Bus.Bus", b =>
                {
                    b.Property<Guid>("BusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AppSagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("CodeChauffeur")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeCircuit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentOccupancy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMEI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastOccupancyUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPositionAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ModelBus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIMM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BusId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Bus");
                });

            modelBuilder.Entity("CollectManagement.Domain.Bus.BusRuntimeEvent", b =>
                {
                    b.Property<Guid>("BusRuntimeEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IMEI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Occupancy")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("BusRuntimeEventId");

                    b.HasIndex("BusId");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("BusRuntimeEvent");
                });

            modelBuilder.Entity("CollectManagement.Domain.Chantiers.Chantier", b =>
                {
                    b.Property<Guid>("ChantierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CodeClient")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LibelleChantier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontantHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantTTC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nature")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroChantier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChantierId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Chantier");
                });

            modelBuilder.Entity("CollectManagement.Domain.Chauffeurs.Chauffeur", b =>
                {
                    b.Property<Guid>("ChauffeurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CIN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeChauffeur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Externe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RFIDChauffeur")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ChauffeurId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Chauffeur");
                });

            modelBuilder.Entity("CollectManagement.Domain.Circuits.Circuit", b =>
                {
                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeCircuit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodePCArrivee")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodePCDepart")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Couleur")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("DureeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LibelleCircuit")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CircuitId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Circuit");
                });

            modelBuilder.Entity("CollectManagement.Domain.Circuits.CircuitPointCollecte", b =>
                {
                    b.Property<Guid>("CircuitPointCollecteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodePointCollecte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("LibellePointCollecte")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ordre")
                        .HasColumnType("int");

                    b.HasKey("CircuitPointCollecteId");

                    b.HasIndex("CircuitId");

                    b.ToTable("CircuitPointCollecte");
                });

            modelBuilder.Entity("CollectManagement.Domain.Employes.Employe", b =>
                {
                    b.Property<Guid>("EmployeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CodeBus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeCircuit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeGouvernorat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodePointCollecte")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeRegion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeShift")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RFID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeEmploye")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("EmployeSimple");

                    b.HasKey("EmployeId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Employe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Equipes.Equipe", b =>
                {
                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeClient")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeEntrepot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeEquipe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeFournisseur")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeTarif")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeVehicule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsInternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LibelleEquipe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EquipeId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Equipe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Gouvernorats.Gouvernorat", b =>
                {
                    b.Property<Guid>("GouvernoratId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeGouvernorat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LibelleGouvernorat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GouvernoratId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Gouvernorat");

                    b.HasData(
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-51c6-2689-b96c31cd6869"),
                            CodeGouvernorat = "11",
                            IsActive = true,
                            LibelleGouvernorat = "Tunis",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-ab24-93ca-772b96003f6d"),
                            CodeGouvernorat = "12",
                            IsActive = true,
                            LibelleGouvernorat = "Ariana",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-52ca-a3fc-417b0de18491"),
                            CodeGouvernorat = "13",
                            IsActive = true,
                            LibelleGouvernorat = "Ben Arous",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-f572-f17d-9eebacd54dbd"),
                            CodeGouvernorat = "14",
                            IsActive = true,
                            LibelleGouvernorat = "Manouba",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-33d5-95e0-30cf429da5ce"),
                            CodeGouvernorat = "21",
                            IsActive = true,
                            LibelleGouvernorat = "Nabeul",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-400a-551d-b6bcf384e68e"),
                            CodeGouvernorat = "22",
                            IsActive = true,
                            LibelleGouvernorat = "Zaghouan",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-8e6b-d8d3-14a128e0c510"),
                            CodeGouvernorat = "23",
                            IsActive = true,
                            LibelleGouvernorat = "Bizerte",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-4781-d6b6-f9675e924174"),
                            CodeGouvernorat = "31",
                            IsActive = true,
                            LibelleGouvernorat = "Béja",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-b84c-3034-a488958fdc05"),
                            CodeGouvernorat = "32",
                            IsActive = true,
                            LibelleGouvernorat = "Jendouba",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-2673-5615-c7fe32a4a41c"),
                            CodeGouvernorat = "33",
                            IsActive = true,
                            LibelleGouvernorat = "Le Kef",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-8918-a75b-723de9d62126"),
                            CodeGouvernorat = "34",
                            IsActive = true,
                            LibelleGouvernorat = "Siliana",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-e3a7-48f1-f64d534d1d5e"),
                            CodeGouvernorat = "41",
                            IsActive = true,
                            LibelleGouvernorat = "Kairouan",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-6212-734d-2f967c9d4319"),
                            CodeGouvernorat = "42",
                            IsActive = true,
                            LibelleGouvernorat = "Kasserine",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-0930-135c-4e6b70870bd0"),
                            CodeGouvernorat = "43",
                            IsActive = true,
                            LibelleGouvernorat = "Sidi Bouzid",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-b965-6563-221bd611cd04"),
                            CodeGouvernorat = "51",
                            IsActive = true,
                            LibelleGouvernorat = "Sousse",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-0dd8-e283-3ca630c73458"),
                            CodeGouvernorat = "52",
                            IsActive = true,
                            LibelleGouvernorat = "Monastir",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-5b4c-6be2-6bbdc1b47079"),
                            CodeGouvernorat = "53",
                            IsActive = true,
                            LibelleGouvernorat = "Mahdia",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-809a-6df3-17738bce5864"),
                            CodeGouvernorat = "61",
                            IsActive = true,
                            LibelleGouvernorat = "Sfax",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-cf32-e510-5f0bb007f345"),
                            CodeGouvernorat = "71",
                            IsActive = true,
                            LibelleGouvernorat = "Gafsa",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-d409-25a3-3f0e60a408ab"),
                            CodeGouvernorat = "72",
                            IsActive = true,
                            LibelleGouvernorat = "Tozeur",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-bdc6-f11a-0dcf6b479589"),
                            CodeGouvernorat = "73",
                            IsActive = true,
                            LibelleGouvernorat = "Kebili",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-40a2-8178-9b64bbc2c7c8"),
                            CodeGouvernorat = "81",
                            IsActive = true,
                            LibelleGouvernorat = "Gabès",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-9dab-2f56-5cfc8755fc12"),
                            CodeGouvernorat = "82",
                            IsActive = true,
                            LibelleGouvernorat = "Médenine",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        },
                        new
                        {
                            GouvernoratId = new Guid("019e5065-e327-0f7a-31ac-7383772b901c"),
                            CodeGouvernorat = "83",
                            IsActive = true,
                            LibelleGouvernorat = "Tataouine",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        });
                });

            modelBuilder.Entity("CollectManagement.Domain.Modems.Modem", b =>
                {
                    b.Property<Guid>("ModemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModelModem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ModemId");

                    b.HasIndex("IMEI")
                        .IsUnique();

                    b.HasIndex("SocieteId");

                    b.ToTable("Modem");
                });

            modelBuilder.Entity("CollectManagement.Domain.OrdresTravail.OrdreTravail", b =>
                {
                    b.Property<Guid>("OrdreTravailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeClient")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeEquipe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeVehicule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("EtatOT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Libelle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("NumeroBonCommande")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroChantier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroConvention")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroOrdreTravail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrdreTravailId");

                    b.HasIndex("SocieteId");

                    b.ToTable("OrdreTravail");
                });

            modelBuilder.Entity("CollectManagement.Domain.OrdresTravail.OrdreTravailDetail", b =>
                {
                    b.Property<Guid>("OrdreTravailDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeEntrepot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeUnite")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleArticle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Montant")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("OrdreTravailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PrixUnitaireHT")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Quantite")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TauxTVA")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("OrdreTravailDetailId");

                    b.HasIndex("OrdreTravailId");

                    b.ToTable("OrdreTravailDetail");
                });

            modelBuilder.Entity("CollectManagement.Domain.PointsCollecte.PointCollecte", b =>
                {
                    b.Property<Guid>("PointCollecteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeGouvernorat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodePointCollecte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeRegion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("LibellePointCollecte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PointCollecteId");

                    b.HasIndex("SocieteId");

                    b.ToTable("PointCollecte");
                });

            modelBuilder.Entity("CollectManagement.Domain.Rattachements.Rattachement", b =>
                {
                    b.Property<Guid>("RattachementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeClient")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Cout")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRattachement")
                        .HasColumnType("date");

                    b.Property<string>("Emplacement")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Exercice")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HeureFin")
                        .HasColumnType("time");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsInternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nature")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroChantier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroRattachement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarque")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RattachementId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Rattachement");
                });

            modelBuilder.Entity("CollectManagement.Domain.Rattachements.RattachementArticle", b =>
                {
                    b.Property<Guid>("RattachementArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeEntrepot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeUnite")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateBonLivraison")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Libelle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroBonLivraison")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PrixRevient")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("Quantite")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("RattachementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TauxTVA")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TypeRattachement")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RattachementArticleId");

                    b.HasIndex("RattachementId");

                    b.HasIndex("SocieteId");

                    b.ToTable("RattachementArticle");
                });

            modelBuilder.Entity("CollectManagement.Domain.Rattachements.RattachementEmploye", b =>
                {
                    b.Property<Guid>("RattachementEmployeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Cout")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("CoutGlobal")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HeureFin")
                        .HasColumnType("time");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPrenom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("NombreHeure")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("RattachementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeRattachement")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RattachementEmployeId");

                    b.HasIndex("RattachementId");

                    b.HasIndex("SocieteId");

                    b.ToTable("RattachementEmploye");
                });

            modelBuilder.Entity("CollectManagement.Domain.Regions.Region", b =>
                {
                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeGouvernorat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeRegion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LibelleRegion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RegionId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("CollectManagement.Domain.Reseaux.Reseau", b =>
                {
                    b.Property<Guid>("ReseauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GmtPlus")
                        .HasColumnType("int");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,10)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rayon")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TimeToleranceMinute")
                        .HasColumnType("int");

                    b.HasKey("ReseauId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Reseau");
                });

            modelBuilder.Entity("CollectManagement.Domain.Shifts.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeShift")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HeureFin")
                        .HasColumnType("time");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JourSemaine")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LibelleShift")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShiftId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("CollectManagement.Domain.Sites.Site", b =>
                {
                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("LibelleSite")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Rayon")
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("Siege")
                        .HasColumnType("bit");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TimeMinute")
                        .HasColumnType("int");

                    b.HasKey("SiteId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("CollectManagement.Domain.Societes.Societe", b =>
                {
                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("Capital")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<string>("CodePostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodeSociete")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOverture")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Fax1")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Fax2")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Initiales")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatriculeFiscal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pays")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rne")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone1")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Telephone2")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Tva")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SocieteId");

                    b.ToTable("Societe");

                    b.HasData(
                        new
                        {
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0"),
                            Capital = 0m,
                            CodeSociete = "CST",
                            DateOverture = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@cst.tn",
                            Initiales = "CST",
                            MatriculeFiscal = "MF-CST-001",
                            Nom = "CST",
                            Rc = "RC-CST-001",
                            Rne = "RNE-CST-001",
                            Tva = "TVA-CST-001"
                        });
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Entities.RoleUtilisateur", b =>
                {
                    b.Property<Guid>("RoleUtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleRoleUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleUtilisateurId");

                    b.HasIndex("SocieteId");

                    b.ToTable("RoleUtilisateur");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Entities.UtilisateurSite", b =>
                {
                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UtilisateurId", "SiteId");

                    b.HasIndex("SiteId");

                    b.ToTable("UtilisateurSite");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Utilisateur", b =>
                {
                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("RoleUtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UtilisateurId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomUtilisateur")
                        .IsUnique();

                    b.HasIndex("RoleUtilisateurId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Utilisateur");

                    b.HasData(
                        new
                        {
                            UtilisateurId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0"),
                            Email = "admin@cst.tn",
                            IsActive = true,
                            Nom = "Admin",
                            NomUtilisateur = "admin",
                            Password = "E2CF9A6F4CFCA46F74FC0E4CF7A5B278D3C20D9178E0DB936DBB3CF8E614C89E4D1C33229F39A457014D2D581CAA3DCE7F49C53803A176A4F891A9EB1D5A34BA",
                            Prenom = "CST",
                            SocieteId = new Guid("018b1055-d0b7-de38-752f-1b18f580c2e0")
                        });
                });

            modelBuilder.Entity("CollectManagement.Domain.Bus.Bus", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Bus.BusRuntimeEvent", b =>
                {
                    b.HasOne("CollectManagement.Domain.Bus.Bus", null)
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollectManagement.Domain.Chantiers.Chantier", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Chauffeurs.Chauffeur", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Circuits.Circuit", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Circuits.CircuitPointCollecte", b =>
                {
                    b.HasOne("CollectManagement.Domain.Circuits.Circuit", null)
                        .WithMany("CircuitPointsCollecte")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollectManagement.Domain.Employes.Employe", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Equipes.Equipe", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Gouvernorats.Gouvernorat", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Modems.Modem", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.OrdresTravail.OrdreTravail", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.OrdresTravail.OrdreTravailDetail", b =>
                {
                    b.HasOne("CollectManagement.Domain.OrdresTravail.OrdreTravail", null)
                        .WithMany("OrdreTravailDetails")
                        .HasForeignKey("OrdreTravailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollectManagement.Domain.PointsCollecte.PointCollecte", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Rattachements.Rattachement", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Rattachements.RattachementArticle", b =>
                {
                    b.HasOne("CollectManagement.Domain.Rattachements.Rattachement", "Rattachement")
                        .WithMany()
                        .HasForeignKey("RattachementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rattachement");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Rattachements.RattachementEmploye", b =>
                {
                    b.HasOne("CollectManagement.Domain.Rattachements.Rattachement", "Rattachement")
                        .WithMany()
                        .HasForeignKey("RattachementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rattachement");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Regions.Region", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Reseaux.Reseau", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Shifts.Shift", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Sites.Site", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Entities.RoleUtilisateur", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("CollectManagement.Domain.Utilisateurs.Entities.Navigation", "Navigations", b1 =>
                        {
                            b1.Property<string>("NavigationId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid>("RoleUtilisateurId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Actions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NavigationId", "RoleUtilisateurId");

                            b1.HasIndex("RoleUtilisateurId");

                            b1.ToTable("Navigation");

                            b1.WithOwner()
                                .HasForeignKey("RoleUtilisateurId");

                            b1.OwnsMany("CollectManagement.Domain.Utilisateurs.Entities.NavigationSection", "Sections", b2 =>
                                {
                                    b2.Property<string>("SectionId")
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("Actions")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("NavigationId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<Guid>("NavigationRoleUtilisateurId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("SectionId");

                                    b2.HasIndex("NavigationId", "NavigationRoleUtilisateurId");

                                    b2.ToTable("NavigationSection");

                                    b2.WithOwner()
                                        .HasForeignKey("NavigationId", "NavigationRoleUtilisateurId");
                                });

                            b1.Navigation("Sections");
                        });

                    b.Navigation("Navigations");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Entities.UtilisateurSite", b =>
                {
                    b.HasOne("CollectManagement.Domain.Sites.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollectManagement.Domain.Utilisateurs.Utilisateur", "Utilisateur")
                        .WithMany("Sites")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Utilisateur", b =>
                {
                    b.HasOne("CollectManagement.Domain.Utilisateurs.Entities.RoleUtilisateur", "RoleUtilisateur")
                        .WithMany()
                        .HasForeignKey("RoleUtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RoleUtilisateur");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Circuits.Circuit", b =>
                {
                    b.Navigation("CircuitPointsCollecte");
                });

            modelBuilder.Entity("CollectManagement.Domain.OrdresTravail.OrdreTravail", b =>
                {
                    b.Navigation("OrdreTravailDetails");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Utilisateur", b =>
                {
                    b.Navigation("Sites");
                });
#pragma warning restore 612, 618
        }
    }
}
