// <auto-generated />
using System;
using CollectManagement.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324143240_AddChantier")]
    partial class AddChantier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollectManagement.Domain.Bus.Bus", b =>
                {
                    b.Property<Guid>("BusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AppSagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("CodeCircuit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMEI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModelBus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIMM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BusId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Bus");
                });

            modelBuilder.Entity("CollectManagement.Domain.Chantiers.Chantier", b =>
                {
                    b.Property<Guid>("ChantierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CodeClient")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LibelleChantier")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MontantHT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MontantTTC")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nature")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroChantier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChantierId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Chantier");
                });

            modelBuilder.Entity("CollectManagement.Domain.Circuits.Circuit", b =>
                {
                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeCircuit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodePCArrivee")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodePCDepart")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Couleur")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("DureeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LibelleCircuit")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CircuitId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Circuit");
                });

            modelBuilder.Entity("CollectManagement.Domain.Circuits.CircuitPointCollecte", b =>
                {
                    b.Property<Guid>("CircuitPointCollecteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodePointCollecte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("LibellePointCollecte")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ordre")
                        .HasColumnType("int");

                    b.HasKey("CircuitPointCollecteId");

                    b.HasIndex("CircuitId");

                    b.ToTable("CircuitPointCollecte");
                });

            modelBuilder.Entity("CollectManagement.Domain.Employes.Employe", b =>
                {
                    b.Property<Guid>("EmployeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CodeCircuit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeGouvernorat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodePointCollecte")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeRegion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeShift")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RFID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Employe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Equipes.Equipe", b =>
                {
                    b.Property<Guid>("EquipeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeClient")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeEntrepot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeEquipe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeFournisseur")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeTarif")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeVehicule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsInternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LibelleEquipe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EquipeId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Equipe");
                });

            modelBuilder.Entity("CollectManagement.Domain.OrdresTravail.OrdreTravail", b =>
                {
                    b.Property<Guid>("OrdreTravailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeClient")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeEquipe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeVehicule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("EtatOT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Libelle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("NumeroBonCommande")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroChantier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroConvention")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroOrdreTravail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrdreTravailId");

                    b.HasIndex("SocieteId");

                    b.ToTable("OrdreTravail");
                });

            modelBuilder.Entity("CollectManagement.Domain.OrdresTravail.OrdreTravailDetail", b =>
                {
                    b.Property<Guid>("OrdreTravailDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeArticle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeEntrepot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeUnite")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleArticle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Montant")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("OrdreTravailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PrixUnitaireHT")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Quantite")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TauxTVA")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("OrdreTravailDetailId");

                    b.HasIndex("OrdreTravailId");

                    b.ToTable("OrdreTravailDetail");
                });

            modelBuilder.Entity("CollectManagement.Domain.PointsCollecte.PointCollecte", b =>
                {
                    b.Property<Guid>("PointCollecteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeGouvernorat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodePointCollecte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeRegion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("LibellePointCollecte")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PointCollecteId");

                    b.HasIndex("SocieteId");

                    b.ToTable("PointCollecte");
                });

            modelBuilder.Entity("CollectManagement.Domain.Rattachements.Rattachement", b =>
                {
                    b.Property<Guid>("RattachementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeClient")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Cout")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRattachement")
                        .HasColumnType("date");

                    b.Property<string>("Emplacement")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Exercice")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HeureFin")
                        .HasColumnType("time");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsInternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nature")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroChantier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroRattachement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarque")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RattachementId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Rattachement");
                });

            modelBuilder.Entity("CollectManagement.Domain.Shifts.Shift", b =>
                {
                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeShift")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("HeureDebut")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("HeureFin")
                        .HasColumnType("time");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("JourSemaine")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LibelleShift")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShiftId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("CollectManagement.Domain.Societes.Societe", b =>
                {
                    b.Property<Guid>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Capital")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<string>("CodeSociete")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOverture")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Fax1")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Fax2")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatriculeFiscal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rne")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone1")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Telephone2")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("SocieteId");

                    b.ToTable("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Entities.RoleUtilisateur", b =>
                {
                    b.Property<Guid>("RoleUtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibelleRoleUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleUtilisateurId");

                    b.ToTable("RoleUtilisateur");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Utilisateur", b =>
                {
                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateInsertion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InsererPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifierPar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("RoleUtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SocieteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UtilisateurId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomUtilisateur")
                        .IsUnique();

                    b.HasIndex("RoleUtilisateurId");

                    b.HasIndex("SocieteId");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("CollectManagement.Domain.Bus.Bus", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Chantiers.Chantier", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Circuits.Circuit", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Circuits.CircuitPointCollecte", b =>
                {
                    b.HasOne("CollectManagement.Domain.Circuits.Circuit", null)
                        .WithMany("CircuitPointsCollecte")
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollectManagement.Domain.Employes.Employe", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Equipes.Equipe", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.OrdresTravail.OrdreTravail", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.OrdresTravail.OrdreTravailDetail", b =>
                {
                    b.HasOne("CollectManagement.Domain.OrdresTravail.OrdreTravail", null)
                        .WithMany("OrdreTravailDetails")
                        .HasForeignKey("OrdreTravailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CollectManagement.Domain.PointsCollecte.PointCollecte", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Rattachements.Rattachement", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Shifts.Shift", b =>
                {
                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Entities.RoleUtilisateur", b =>
                {
                    b.OwnsMany("CollectManagement.Domain.Utilisateurs.Entities.Navigation", "Navigations", b1 =>
                        {
                            b1.Property<string>("NavigationId")
                                .HasColumnType("nvarchar(50)");

                            b1.Property<Guid>("RoleUtilisateurId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Actions")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NavigationId", "RoleUtilisateurId");

                            b1.HasIndex("RoleUtilisateurId");

                            b1.ToTable("Navigation");

                            b1.WithOwner()
                                .HasForeignKey("RoleUtilisateurId");

                            b1.OwnsMany("CollectManagement.Domain.Utilisateurs.Entities.NavigationSection", "Sections", b2 =>
                                {
                                    b2.Property<string>("SectionId")
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("Actions")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("NavigationId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<Guid>("NavigationRoleUtilisateurId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("SectionId");

                                    b2.HasIndex("NavigationId", "NavigationRoleUtilisateurId");

                                    b2.ToTable("NavigationSection");

                                    b2.WithOwner()
                                        .HasForeignKey("NavigationId", "NavigationRoleUtilisateurId");
                                });

                            b1.Navigation("Sections");
                        });

                    b.Navigation("Navigations");
                });

            modelBuilder.Entity("CollectManagement.Domain.Utilisateurs.Utilisateur", b =>
                {
                    b.HasOne("CollectManagement.Domain.Utilisateurs.Entities.RoleUtilisateur", "RoleUtilisateur")
                        .WithMany()
                        .HasForeignKey("RoleUtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CollectManagement.Domain.Societes.Societe", "Societe")
                        .WithMany()
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RoleUtilisateur");

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("CollectManagement.Domain.Circuits.Circuit", b =>
                {
                    b.Navigation("CircuitPointsCollecte");
                });

            modelBuilder.Entity("CollectManagement.Domain.OrdresTravail.OrdreTravail", b =>
                {
                    b.Navigation("OrdreTravailDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
